apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: {{ include "fraud-api.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "fraud-api.fullname" . }}
  service:
    port: {{ .Values.service.port }}
  analysis:
    interval: 1m
    threshold: 10
    maxWeight: 50
    stepWeight: 10
    metrics:
    - name: request-success-rate
      threshold: 99
      interval: 1m
    - name: request-duration
      threshold: 500      # 500ms latency threshold
      interval: 1m
    webhooks:
      - name: health-check
        type: pre-rollout
        url: http://{{ include "fraud-api.fullname" . }}-canary/health
        timeout: 15s