apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-api-deployment
  labels:
    app: fraud-api
  annotations:
    flagger.app/canary: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-api
  template:
    metadata:
      labels:
        app: fraud-api
    spec:
      containers:
        - name: fraud-api
          image: derabyte/fraud-api:latest
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: "1000m"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: MLFLOW_TRACKING_URI
              valueFrom:
                configMapKeyRef:
                  name: api-config-map
                  key: mlflow_tracking_url
            - name: MODEL_URI
              valueFrom:
                configMapKeyRef:
                  name: api-config-map
                  key: model_uri
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-api-service
  labels:
    app: fraud-api
spec:
  selector:
    app: fraud-api
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
