apiVersion: v2
name: mlflow
description: MLflow Tracking Server
type: application
version: 0.1.0
appVersion: "2.3.0"
icon: https://raw.githubusercontent.com/mlflow/mlflow/master/docs/source/_static/MLflow-logo-final-black.png

dependencies:
  - name: postgresql
    version: "12.8.5"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: minio
    version: "5.0.11"
    repository: "https://charts.min.io/"
    condition: minio.enabled
