# Core configuration
replicaCount: 1

# Image configuration
image:
  repository: ghcr.io/mlflow/mlflow
  tag: latest
  pullPolicy: IfNotPresent

# Service configuration
service:
  type: NodePort
  port: 5000
  nodePort: 30500

# Resources
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

# ConfigMap configuration
configMap:
  enabled: true
  data:
    mlflow_tracking_uri: http://mlflow:5000
    backend_store_uri: postgresql://mlflow:mlflow@postgres:5432/mlflow
    artifact_root: s3://k8s-mlflow/
    aws_access_key_id: minioadmin
    aws_secret_access_key: minioadmin

# Command configuration
command:
  enabled: true
  command: ["gunicorn"]
  args:
    - --workers=4
    - --timeout=60
    - --bind=0.0.0.0:5000
    - mlflow.server:app# Core configuration
replicaCount: 1

# Image configuration
image:
  repository: ghcr.io/mlflow/mlflow
  tag: latest
  pullPolicy: IfNotPresent

# Service configuration
service:
  type: NodePort
  port: 5000
  nodePort: 30500

# Resources
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

# ConfigMap configuration
configMap:
  enabled: true
  data:
    mlflow_tracking_uri: http://mlflow:5000
    backend_store_uri: postgresql://mlflow:mlflow@postgres:5432/mlflow
    artifact_root: s3://k8s-mlflow/
    aws_access_key_id: minioadmin
    aws_secret_access_key: minioadmin

# Command configuration
command:
  enabled: true
  command: ["gunicorn"]
  args:
    - --workers=4
    - --timeout=60
    - --bind=0.0.0.0:5000
    - mlflow.server:app