# Core configuration
replicaCount: 1

# Image configuration
image:
  repository: derabyte/fraud-monitoring
  tag: latest
  pullPolicy: IfNotPresent

# Service configuration
service:
  type: ClusterIP
  port: 5000

# Resources
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

# ConfigMap configuration
configMap:
  enabled: true
  data:
    reference_path: /app/reference.parquet
    monitoring_path: /app/monitoring.parquet
    drift_threshold: "0.1"
    performance_threshold: "0.95"