replicaCount: 1

image:
  repository: derabyte/fraud-monitoring
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

configMap:
  enabled: true
  data:
    reference_path: /app/reference.parquet
    monitoring_path: /app/monitoring.parquet
    drift_threshold: "0.1"
    performance_threshold: "0.95"