apiVersion: v1
kind: ConfigMap
metadata:
  name: evidently-config
  namespace: mlops
data:
  # Maximum allowed deviation from reference data distribution
  drift_threshold: "0.1"    # 10% threshold for statistical drift tests
  
  # Minimum required model performance compared to baseline
  performance_threshold: "0.95"    # 95% of baseline model performance
  
  # Data paths for monitoring
  reference_data_path: "s3://mlflow/reference/data.csv"
  metrics_path: "s3://mlflow/metrics"
  
  # Monitoring configuration
  monitoring_interval: "1h"        # Check every hour
  alert_threshold: "3"            # Alert after 3 consecutive failures