apiVersion: apps/v1
kind: Deployment
metadata:
  name: evidently
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evidently
  template:
    metadata:
      labels:
        app: evidently
    spec:
      containers:
        - name: evidently
          image: evidently-service:latest  # We'll need to build this
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: evidently-config
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "250m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: evidently-service
  namespace: mlops
spec:
  selector:
    app: evidently
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP    # Adding this back for explicitness
      name: http
  type: ClusterIP