apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - image: ghcr.io/mlflow/mlflow:v2.21.2
        name: mlflow
        ports:
          - containerPort: 5000
        env:  # use configMapKeyRef
          - name: MLFLOW_TRACKING_URI
            value: http://mlflow:5000
          - name: BACKEND_STORE_URI
            value: postgresql://mlflow:mlflow@postgres:5432/mlflow
          - name: ARTIFACT_ROOT
            value: s3://k8s-mlflow/
          - name: AWS_ACCESS_KEY_ID
            value: minioadmin
          - name: AWS_SECRET_ACCESS_KEY
            value: minioadmin
        command: [ "gunicorn" ]
        args:
          - --workers=4
          - --timeout=60
          - --bind=0.0.0.0:5000
          - mlflow.server:app
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
spec:
  selector:
    app: mlflow
  type: NodePort
  ports:
    - name: node-port
      port: 5000
      targetPort: 5000
      nodePort: 30500
