apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-config-map
data:
    mlflow_tracking_uri: http://mlflow:5000
    backend_store_uri: postgresql://mlflow:mlflow@postgres:5432/mlflow
    artifact_root: s3://k8s-mlflow/
    aws_access_key_id: minioadmin
    aws_secret_access_key: minioadmin