apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fraud-api.fullname" . }}
  labels:
    {{- include "fraud-api.labels" . | nindent 4 }}
  annotations:
    flagger.app/canary: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fraud-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fraud-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.probes.liveness | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.probes.readiness | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.volumes.modelCache.enabled }}
          volumeMounts:
            - name: model-cache
              mountPath: {{ .Values.volumes.modelCache.mountPath }}
          {{- end }}
      {{- if .Values.volumes.modelCache.enabled }}
      volumes:
        - name: model-cache
          emptyDir:
            sizeLimit: {{ .Values.volumes.modelCache.size }}
      {{- end }}