# Default values for fraud-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Core configuration
replicaCount: 1

image:
  repository: derabyte/fraud-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

probes:
  liveness:
    path: /
    port: http
  readiness:
    path: /
    port: http

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Model configuration
model:
  uri: "models:/credit-card-xgboost/1"

# MLflow configuration
mlflow:
  url: http://mlflow:5000
